Added post-install script to migrate KafkaChannel to v1beta1
knative-sandbox/eventing-kafka pull request #448
Opened 2021-03-10 09:37 UTC by slinkydeveloper

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Followup of #446

## Proposed Changes

- 🧽 Added a post-install migration job to migrate KafkaChannel to v1beta1

**Release Note**

```release-note
🧽 Added a post-install migration job to migrate KafkaChannel to v1beta1. You must run it after installing eventing-kafka 0.22
```

**Docs**

2021-03-10 09:48 UTC, aliok commented
Can you rebase this once https://github.com/knative-sandbox/eventing-kafka/pull/446 is merged?

2021-03-10 10:26 UTC, slinkydeveloper commented
@aliok this is ready for review

2021-03-10 10:27 UTC, aliok approved these changes, later dismissed
/lgtm
/approve

Looks good!

2021-03-10 10:29 UTC, devguyio requested changes, later dismissed
I believe this must be a pre-install job. v0.22 must end up with a KafkaChannel CRD that says
```yaml
- name: v1alpha1
  served: false
  storage: false
- name: v1beta1 
  served: true
  storage: true
```

2021-03-10 10:36 UTC, aliok commented
/hold

2021-03-10 12:44 UTC, matzew commented on config/post-install/clusterrole.yaml
> +    eventing.knative.dev/release: devel
same regarding the label value

2021-03-10 12:44 UTC, matzew commented on config/post-install/serviceaccount.yaml
> +    eventing.knative.dev/release: devel
same... you get it @slinkydeveloper  :smile:

2021-03-10 12:53 UTC, devguyio commented
I was hoping we'd not end up in a state where we are the only object in `messaging.knative.dev` that's still serving v1alpha1. But if we want to play it 100% safe we should have a release that has storage on v1beta, and still serves v1alpha1 in order to allow for safe storage migration in case the user forgot to run the migration job. TL;DR that's how I understand our options:
- Option1: Have storage and serving migration as pre-install
    - Pros:
        - User ends up with no v1alpha1 objects in messaging.knative.dev 
        - Faster cut / getting rid of dangling v1alpha1 work
    - Cons:
        - Upgrading users might run into issue if they forgot to run the pre-install job
- Option2: Have storage migration as post-install , and stop serving in 0.23
    - Pros:
        - Upgrading users have a way to fix things in case they forgot to run the migration job
    - Cons:
        - We will end up being the only channel in the sandbox that still serves v1alpha1 
        - We still need to plan the removal work if v1alpha1 in following versions

I feel maybe we should cater for upgrading user safety and go for Option 2 indeed.  Let's un-hold once we get an [answer here](https://github.com/knative-sandbox/eventing-kafka/issues/426#issuecomment-795162530)

2021-03-10 12:58 UTC, matzew commented
A real problem happens if both storage/serve go from true/true to false/false in just one release.

Context for one of the most painful things I noticed with this so far: 
https://github.com/knative/eventing/issues/4455

2021-03-10 13:04 UTC, matzew commented
> We will end up being the only channel in the sandbox that still serves v1alpha1

To me that is not a contra point. It is what it is. Better than some `pre-job` nightmare. AND the removal work of the _duck v1alpha1 shapes_ is needed anyways, right  ? 


Sounds like option 2 is the way to go. for 0.22 and on .23 we do the switch to serve: false

2021-03-10 14:10 UTC, slinkydeveloper commented
> Option2: Have storage migration as post-install , and stop serving in 0.23 

ATM I'm pursuing this solution :smile:

2021-03-18 08:42 UTC, aliok approved these changes
/lgtm
/approve
/unhold

The discussion is here: https://github.com/knative-sandbox/eventing-kafka/issues/426

2021-03-18 08:43 UTC, merged